FROM dockerworld/centos6:base

MAINTAINER Eric Mugerwa <ericmdev@gmail.com>

LABEL version="1.0"
LABEL description="Node.js, npm"

# install npm
RUN yum install npm -y

# install nodejs
RUN yum install nodejs -y

# yum clean all
RUN yum clean all
