FROM centos:6

MAINTAINER Cein Markey <hi@ceinmarkey.co.uk>

LABEL version="1.0"
LABEL description="Perl, Git, Vim"

RUN yum update -y
RUN yum install perl -y
RUN yum install git -y
RUN yum install vim -y
RUN yum clean all